`include "CHIP.v"
`include "mul.v"
`include "RVC_decomp.v"
`include "Dcache.v"
`include "Icache.v"
`include "core_RVC_mulpipe.v"
`include "register_file.v"
`include "alu.v"
`include "imm_gen.v"
`include "control.v"
`include "forwarding.v"
`include "hazard_dect.v"
/// Add other verilog files here for example: `include "cache.v"